# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate: 6
paginate_path: /page:num/

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "做游戏的景夫"
description:	       "不追热点 不赶时髦 专注研究游戏引擎技术"
author:              "景夫"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml
